  # This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require_relative 'fastfile_helpers.rb'

default_platform(:ios)

platform :ios do
  
  before_all do
    setup_circle_ci
  end

  desc "Build simulator app"
  lane :build_app_for_simulator do
    build_app(
      scheme: "dsnp-wallet",
      workspace: "./dsnp-wallet.xcworkspace",
      derived_data_path: derived_data_path,
      skip_package_ipa: true,
      skip_archive: true,
      destination: "generic/platform=iOS Simulator"
  )
  end

  desc "Build real device app"
  lane :build_for_ios do
    build_app(
      export_method: "development",
      scheme: "dsnp-wallet",
      workspace: "./dsnp-wallet.xcworkspace",
      derived_data_path: derived_data_path,
      output_name: "dsnp-wallet.ipa",
      destination: "generic/platform=iOS",
      clean: true,
      skip_package_ipa: false,
      xcargs: "-allowProvisioningUpdates"
    )
  end

  desc "Archiving the binary app"
  lane :zip_simulator_bin do
    zip(
      path: derived_data_path + "Build/Products/Debug-iphonesimulator/DSNP-Wallet.app",
      output_path: derived_data_path + "Build/Products/Debug-iphonesimulator/DSNP-Wallet.zip"
    )
  end

  # Use fastlane appcenter_upload_sim_app env:dev to upload 'dev' version of the app to app_center 
  # Use fastlane appcenter_upload_sim_app env:stg to upload 'stg' version of the app to the app_center 
  # requires plugin -> fastlane add_plugin appcenter
  desc "Upload the simulator app to app center"
  lane :appcenter_upload_sim_app do | options | 
    appcenter_upload(
      api_token: ENV["APPCENTER_API_KEY"],
      owner_name: "Unfinished",
      app_name: "standalone-wallet-simulator-" + options[:"env"],
      version: options[:"build_version"], #TODO needs to be 
      file: derived_data_path + "Build/Products/Debug-iphonesimulator/DSNP-Wallet.zip"
    )
  end

  # Use fastlane appcenter_upload_app env:dev to upload 'dev' version of the app to app_center 
  # Use fastlane appcenter_upload_app env:stg to upload 'stg' version of the app to the app_center 
  # requires plugin -> fastlane add_plugin appcenter
  desc "Upload the real app to app center"
  lane :appcenter_upload_app do | options | 
    appcenter_upload(
      api_token: ENV["APPCENTER_API_KEY"],
      owner_name: "Unfinished",
      app_name: "standalone-wallet-" + options[:"env"] + "-1",
      version: options[:"build_version"], #TODO needs to be 
      file: "./dsnp-wallet.ipa"
    )
  end


  desc "Create ios certificate"
  lane :make_ios_cert do
    match(
      git_url: "git@github.com:AmplicaLabs/certificates",
      app_identifier: "com.unfinished.dsnp-wallet",
      username: ENV["APPLE_ID_EMAIL"],
      storage_mode: "git",
      type: "development",
      platform: "ios",
      shallow_clone: true,
      readonly: true
    ) 
  end

  lane :certificates do
    match(app_identifier: ["com.unfinished.dsnp-wallet"])
  end
 
end