  # This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require_relative 'fastfile_helpers.rb'

default_platform(:ios)

platform :ios do
  desc "Build simulator app"
  lane :build_app_for_simulator do
    build_app(
      scheme: "dsnp-wallet",
      project: "./DSNP-Wallet/dsnp-wallet.xcworkspace",
      derived_data_path: derived_data_path,
      skip_package_ipa: true,
      skip_archive: true,
      destination: "generic/platform=iOS Simulator"
  )
  end

  desc "Archiving the binary app"
  lane :zip_simulator_bin do
    zip(
      path: derived_data_path + "Build/Products/Debug-iphonesimulator/DSNP-Wallet.app",
      output_path: derived_data_path + "Build/Products/Debug-iphonesimulator/DSNP-Wallet.zip"
    )
  end

  # Use fastlane appcenter_upload_sim_app env:dev to upload 'dev' version of the app to app_center 
  # Use fastlane appcenter_upload_sim_app env:stg to upload 'stg' version of the app to the app_center 
  # requires plugin -> fastlane add_plugin appcenter
  desc "Upload the app to app center"
  lane :appcenter_upload_sim_app do | options | 
    appcenter_upload(
      api_token: ENV["APPCENTER_API_KEY"],
      owner_name: "Unfinished",
      app_name: "standalone-wallet-simulator-" + options[:"env"],
      version: options[:"build_version"], #TODO needs to be 
      file: derived_data_path + "Build/Products/Debug-iphonesimulator/DSNP-Wallet.zip"
    )
  end

end